### ISSUE TITLE
this ansible role  support elastic 5.0 ?

### ISSUE THREAD

**Issue by mkscala** [torian/ansible-role-elasticsearch#1]

**Comment by torian** [comment]
Not yet, I need to update urls for packages etc. Will do in the next couple of days probably.

**Comment by mkscala** [comment]
Also, please let me know If I will be able to setup the Master, Data, Ingest Node with this new ansible 5.0 role. Do you have any Ansible Role for Kibana/Nginx setup

**Comment by mkscala** [comment]
any luck on the elastic 5.0 ansible playbook, can we have 3 different tags with Master Node, Data Node and Ingest Node?

**Comment by torian** [comment]
@mkscala you can try it out now.

The way the config is set up give you the ability to specify whatever config you want / need, so try it out, and let me know. 

(still need to write the documentation, my bad)

**Comment by mkscala** [comment]
Awesome. Gr8. I will test this weekend and let you know. If we need to add other features.

**Comment by mkscala** [comment]
I don't see any changes for Elastic 5.x. Did you make any changes and how to setup the cluster ?
